### ISSUE TITLE
fatal: bad object type - when Tag should be propagated

### ISSUE THREAD

**Issue by dsentker24** [frankdejonge/use-subsplit-publish#1]
According to [your readme](https://github.com/frankdejonge/use-subsplit-publish#tag-management), the tag should be propagated when it is present.

The first time everything worked. Then i created new commits and a new Release. I expected that the created tag is propagated when use-subsplit-publish starts to work.

The workflow failed instead with the following output:

```
/home/runner/work/example/example/bin/splitsh-lite --prefix=package --origin=tags/44.4.5
4 commits created, 62 commits traversed, in 16ms
65e5cdcd6b617526a3ca2921f821c3d79dccbe43
hash from commit hash origin 65e5cdcd6b617526a3ca2921f821c3d79dccbe43
/usr/bin/git clone git@github.com:dsentker24/repo.git .
Cloning into '.'...
/usr/bin/git tag --points-at 65e5cdcd6b617526a3ca2921f821c3d79dccbe43
65e5cdcd6b617526a3ca2921f821c3d79dccbe43 points-at
/usr/bin/git tag -a 44.4.5 65e5cdcd6b617526a3ca2921f821c3d79dccbe43 -m "Tag: 44.4.5"
fatal: bad object type.
Error: Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by frankdejonge** [comment]
Hi @dsentker24, this looks like the hash doesn't exist yet on the remote. How do you publish your code when you tag commits? It could be that you pushed the tag before the commit existed, so the sub-split wasn't published yet.

**Comment by dsentker24** [comment]
Thank you for your response. Unfortunately my test setup no longer exists so i'll come back to this if i can reproduce it again.
