### ISSUE TITLE
Handling of nested directories

### ISSUE THREAD

**Issue by alexander-schranz** [frankdejonge/use-subsplit-publish#2]
First I really want to thank you for this Github action. It is really the easiest way to create monorepository with suptreesplits 👍 .

I have a configuration like this:

```json
{
    "sub-splits": [
        {
            "name": "SEAL",
            "directory": "src/SEAL",
            "target": "git@github.com:schranz-search/seal.git"
        },
        {
            "name": "SEALReadWriteAdapter",
            "directory": "src/SEAL/Adapter/ReadWrite",
            "target": "git@github.com:schranz-search/seal-read-write-adapter.git"
        },
        {
            "name": "SEALMultiAdapter",
            "directory": "src/SEAL/Adapter/Multi",
            "target": "git@github.com:schranz-search/seal-multi-adapter.git"
        }
    ]
}
```

As configured the `SEALMultiAdapter` and `SEALReadWriteAdapter` are directories inside `SEAL` package. But I don't want that that files are also pushed to `SEAL` repository. So the should be excluded and only be pushed to there own repository.

My structure is very similar to Symfony example the Symfony/messenger has the `Bridge` also inside of it https://github.com/symfony/symfony/tree/6.3/src/Symfony/Component/Messenger but not pushed to the target repo: https://github.com/symfony/messenger.

**Comment by frankdejonge** [comment]
Does the underlying tool even have an option for that? I didn't see their publish configuration, but it could suggest there _is_ an option for that, it may just not be documented.

**Comment by alexander-schranz** [comment]
Sorry forget to update the issue here. Had a chat with Fabien from Symfony, they are using an own version of splitsh supporting this, but currently they not plan to release/maintain that version publicly. So I think currently we can close this issue as not supported by the underlaying tool.
